{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-vault
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: {{ include "app.fullname" . }}-vault
    creationPolicy: Owner
  dataFrom:
    {{- if .Values.vault.common.enabled }}
    # 1. Loaded FIRST → becomes the baseline value
    - extract:
      key: {{ .Values.vault.stage }}/{{ .Values.vault.common.key }}
    {{- end }}
    # 2. Loaded later → the same key will overwrite the value from 'common'.
    - extract:
      key: {{ .Values.vault.stage }}/{{ include "app.fullname" . }}
{{- end }}